# Generated by Django 2.2.6 on 2019-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('fruit', models.CharField(max_length=1)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
