# Generated by Django 2.2.6 on 2019-11-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191121_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(choices=[('F', 'หญิง'), ('M', 'ชาย')], default='F', max_length=1),
        ),
    ]
