# Generated by Django 2.2.6 on 2019-11-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20191121_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='fruit',
            field=models.CharField(choices=[('a', 'แอปเปิ้ล'), ('b', 'มะละกอ'), ('c', 'กล้วย'), ('d', 'ส้ม')], default='c', max_length=1),
        ),
    ]
